"use client";

import { useState } from "react";
import Link from "next/link";
import clsx from "clsx";

export const Header = () => {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  return (
    <>
      <div
        className={clsx(
          "items-center",
          "justify-between",
          "relative",
          "flex",
          "[--bs-gutter-x:1.5rem] [--bs-gutter-y:0]",
          "w-full",
          "max-w-[1140px]",
          "px-[calc(var(--bs-gutter-x)*.5)]",
          "mx-auto",
        )}
      >
        <Link href="/" className={clsx("leading-none", "items-center", "flex")}>
          <h1
            className={clsx(
              "text-3xl",
              "font-normal",
              "uppercase",
              "text-[var(--heading-color)]",
            )}
          >
            Seiyouco
          </h1>
        </Link>

        <nav className="p-0 hidden lg:block">
          <ul
            className={clsx(
              "m-0",
              "p-0",
              "flex",
              "list-none",
              "items-center",
              "space-x-8",
            )}
          >
            <li className={clsx("nowrap px-3.5 py-4", "relative")}>
              <Link
                href="#hero"
                className={clsx(
                  "text-[var(--nav-hover-color)]",
                  "hover:text-[var(--nav-hover-color)]",
                  "text-sm",
                  "px-0.5",
                  "[font-family:var(--nav-font)]",
                  "font-normal",
                  "flex",
                  "items-center",
                  "justify-between",
                  "whitespace-nowrap",
                  "transition-all",
                  "duration-300",
                  "relative",
                  "uppercase",
                  "before:content-['']",
                  "before:absolute",
                  "before:w-full",
                  "before:h-0.5",
                  "before:-bottom-1.5",
                  "before:left-0",
                  "before:bg-[var(--accent-color)]",
                  "before:transition-all",
                  "before:duration-300",
                  "before:ease-in-out",
                  "before:visible",
                  "hover:before:visible",
                )}
              >
                Home
              </Link>
            </li>
            <li className={clsx("nowrap px-3.5 py-4", "relative")}>
              <Link
                href="#about"
                className={clsx(
                  "!text-[var(--nav-color)]",
                  "text-sm",
                  "px-0.5",
                  "[font-family:var(--nav-font)]",
                  "font-normal",
                  "flex",
                  "items-center",
                  "justify-between",
                  "whitespace-nowrap",
                  "transition-all",
                  "duration-300",
                  "relative",
                  "uppercase",
                  "before:content-['']",
                  "before:absolute",
                  "before:h-0.5",
                  "before:-bottom-1.5",
                  "before:left-0",
                  "before:bg-[var(--accent-color)]",
                  "before:transition-all",
                  "before:duration-300",
                  "before:ease-in-out",
                  "before:invisible",
                  "before:w-0",
                  "hover:before:visible",
                  "hover:before:w-full",
                )}
              >
                About
              </Link>
            </li>
            <li className={clsx("nowrap px-3.5 py-4", "relative")}>
              <Link
                href="#services"
                className={clsx(
                  "!text-[var(--nav-color)]",
                  "text-sm",
                  "px-0.5",
                  "[font-family:var(--nav-font)]",
                  "font-normal",
                  "flex",
                  "items-center",
                  "justify-between",
                  "whitespace-nowrap",
                  "transition-all",
                  "duration-300",
                  "relative",
                  "uppercase",
                  "before:content-['']",
                  "before:absolute",
                  "before:h-0.5",
                  "before:-bottom-1.5",
                  "before:left-0",
                  "before:bg-[var(--accent-color)]",
                  "before:transition-all",
                  "before:duration-300",
                  "before:ease-in-out",
                  "before:invisible",
                  "before:w-0",
                  "hover:before:visible",
                  "hover:before:w-full",
                )}
              >
                Services
              </Link>
            </li>
            <li className={clsx("nowrap px-3.5 py-4", "relative")}>
              <Link
                href="#portfolio"
                className={clsx(
                  "!text-[var(--nav-color)]",
                  "text-sm",
                  "px-0.5",
                  "[font-family:var(--nav-font)]",
                  "font-normal",
                  "flex",
                  "items-center",
                  "justify-between",
                  "whitespace-nowrap",
                  "transition-all",
                  "duration-300",
                  "relative",
                  "uppercase",
                  "before:content-['']",
                  "before:absolute",
                  "before:h-0.5",
                  "before:-bottom-1.5",
                  "before:left-0",
                  "before:bg-[var(--accent-color)]",
                  "before:transition-all",
                  "before:duration-300",
                  "before:ease-in-out",
                  "before:invisible",
                  "before:w-0",
                  "hover:before:visible",
                  "hover:before:w-full",
                )}
              >
                Portfolio
              </Link>
            </li>
            <li className={clsx("nowrap px-3.5 py-4", "relative")}>
              <Link
                href="#team"
                className={clsx(
                  "!text-[var(--nav-color)]",
                  "text-sm",
                  "px-0.5",
                  "[font-family:var(--nav-font)]",
                  "font-normal",
                  "flex",
                  "items-center",
                  "justify-between",
                  "whitespace-nowrap",
                  "transition-all",
                  "duration-300",
                  "relative",
                  "uppercase",
                  "before:content-['']",
                  "before:absolute",
                  "before:h-0.5",
                  "before:-bottom-1.5",
                  "before:left-0",
                  "before:bg-[var(--accent-color)]",
                  "before:transition-all",
                  "before:duration-300",
                  "before:ease-in-out",
                  "before:invisible",
                  "before:w-0",
                  "hover:before:visible",
                  "hover:before:w-full",
                )}
              >
                Team
              </Link>
            </li>
            <li className={clsx("nowrap px-3.5 py-4", "relative")}>
              <Link
                href="#contact"
                className={clsx(
                  "!text-[var(--nav-color)]",
                  "text-sm",
                  "px-0.5",
                  "[font-family:var(--nav-font)]",
                  "font-normal",
                  "flex",
                  "items-center",
                  "justify-between",
                  "whitespace-nowrap",
                  "transition-all",
                  "duration-300",
                  "relative",
                  "uppercase",
                  "before:content-['']",
                  "before:absolute",
                  "before:h-0.5",
                  "before:-bottom-1.5",
                  "before:left-0",
                  "before:bg-[var(--accent-color)]",
                  "before:transition-all",
                  "before:duration-300",
                  "before:ease-in-out",
                  "before:invisible",
                  "before:w-0",
                  "hover:before:visible",
                  "hover:before:w-full",
                )}
              >
                Contact
              </Link>
            </li>
          </ul>
        </nav>

        {/* <button
          className="lg:hidden text-2xl"
          onClick={() => setIsMenuOpen(!isMenuOpen)}
        >
          <i className={`bi bi-${isMenuOpen ? "x" : "list"}`}></i>
        </button> */}
      </div>

      {/* Mobile Menu */}
      {isMenuOpen && (
        <div className="lg:hidden bg-white shadow-lg">
          <nav className="container mx-auto px-4 py-4">
            <ul className="space-y-4">
              <li>
                <Link
                  href="#hero"
                  className={clsx(
                    "text-[var(--nav-color)]",
                    "text-sm",
                    "px-0.5",
                    "[font-family:var(--nav-font)]",
                    "font-normal",
                    "flex",
                    "items-center",
                    "justify-between",
                    "whitespace-nowrap",
                    "transition-all",
                    "duration-300",
                    "relative",
                    "uppercase",
                    "hover:text-[var(--nav-hover-color)]",
                  )}
                  onClick={() => setIsMenuOpen(false)}
                >
                  Home
                </Link>
              </li>
              <li>
                <Link
                  href="#about"
                  className={clsx(
                    "text-[var(--nav-color)]",
                    "text-sm",
                    "px-0.5",
                    "[font-family:var(--nav-font)]",
                    "font-normal",
                    "flex",
                    "items-center",
                    "justify-between",
                    "whitespace-nowrap",
                    "transition-all",
                    "duration-300",
                    "relative",
                    "uppercase",
                    "hover:text-[var(--nav-hover-color)]",
                  )}
                  onClick={() => setIsMenuOpen(false)}
                >
                  About
                </Link>
              </li>
              <li>
                <Link
                  href="#services"
                  className={clsx(
                    "text-[var(--nav-color)]",
                    "text-sm",
                    "px-0.5",
                    "[font-family:var(--nav-font)]",
                    "font-normal",
                    "flex",
                    "items-center",
                    "justify-between",
                    "whitespace-nowrap",
                    "transition-all",
                    "duration-300",
                    "relative",
                    "uppercase",
                    "hover:text-[var(--nav-hover-color)]",
                  )}
                  onClick={() => setIsMenuOpen(false)}
                >
                  Services
                </Link>
              </li>
              <li>
                <Link
                  href="#portfolio"
                  className={clsx(
                    "text-[var(--nav-color)]",
                    "text-sm",
                    "px-0.5",
                    "[font-family:var(--nav-font)]",
                    "font-normal",
                    "flex",
                    "items-center",
                    "justify-between",
                    "whitespace-nowrap",
                    "transition-all",
                    "duration-300",
                    "relative",
                    "uppercase",
                    "hover:text-[var(--nav-hover-color)]",
                  )}
                  onClick={() => setIsMenuOpen(false)}
                >
                  Portfolio
                </Link>
              </li>
              <li>
                <Link
                  href="#team"
                  className={clsx(
                    "text-[var(--nav-color)]",
                    "text-sm",
                    "px-0.5",
                    "[font-family:var(--nav-font)]",
                    "font-normal",
                    "flex",
                    "items-center",
                    "justify-between",
                    "whitespace-nowrap",
                    "transition-all",
                    "duration-300",
                    "relative",
                    "uppercase",
                    "hover:text-[var(--nav-hover-color)]",
                  )}
                  onClick={() => setIsMenuOpen(false)}
                >
                  Team
                </Link>
              </li>
              <li>
                <Link
                  href="#contact"
                  className={clsx(
                    "text-[var(--nav-color)]",
                    "text-sm",
                    "px-0.5",
                    "[font-family:var(--nav-font)]",
                    "font-normal",
                    "flex",
                    "items-center",
                    "justify-between",
                    "whitespace-nowrap",
                    "transition-all",
                    "duration-300",
                    "relative",
                    "uppercase",
                    "hover:text-[var(--nav-hover-color)]",
                  )}
                  onClick={() => setIsMenuOpen(false)}
                >
                  Contact
                </Link>
              </li>
            </ul>
          </nav>
        </div>
      )}
    </>
  );
};
