export * from "./Header";
export * from "./Hero";
export * from "./About";
export * from "./Stats";
export * from "./Services";
// export * from "./CallToAction";
// export * from "./Portfolio";
export * from "./Team";
export * from "./Contact";
export * from "./Footer";
export * from "./common";
